version: '3.3'
services:
    postgis:
        container_name: postgis
        image: postgis/postgis:9.5-2.5-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./postgis/data_dir:/var/lib/postgresql/data

    geoserver:
        container_name: geoserver-test
        image: docker.osgeo.org/geoserver:2.23.x
        depends_on:
            - postgis
        ports:
            - 8080:8080
        environment:
            - INSTALL_EXTENSIONS=true
            - STABLE_EXTENSIONS=csw,monitor
            - CORS_ENABLED=true
            - EXTRA_JAVA_OPTS=-Xms128m -Xmx756M -XX:SoftRefLRUPolicyMSPerMB=36000
        volumes:
            - ./data_dir:/opt/geoserver_data
